[package]
name = "lux"
version = "0.1.0"
authors = ["Taketoshi Aono <brn@b6n.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"
libc = "0.2"
bitflags = "1.2"
num-traits = "0.2"
num = "0.4"

[[bin]]
name = "lux"
path = "src/main.rs"